GET http://localhost:8000/products/ HTTP/1.1

###
GET http://localhost:8000/products/3 HTTP/1.1

###
DELETE http://localhost:8000/products/3 HTTP/1.1

###
PUT http://localhost:8000/products/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer < access token >

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer <access token id>

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "Jerry",
    "password": "admintest"
}

###
GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer <access token>

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "<refresh token>"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxNTg3NzQzLCJpYXQiOjE3NzE1ODc0NDMsImp0aSI6IjdhZGNmYmEwMzhjNDRjMmFiNDJjOWU4YWZmNTU3OWY4IiwidXNlcl9pZCI6IjIifQ.VBrano5GZUZOAgNY2uds2OqlcbLpNHNueJwC_QC89zo

###

GET http://localhost:8000/orders/b12d0250-d175-404d-9f04-975c67400f57 HTTP/1.1
Authorization: Bearer <access token>

###

PUT http://localhost:8000/orders/b12d0250-d175-404d-9f04-975c67400f57/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer <access token>

{
    "status": "Confirmed",
    "items": [
        {
            "product": 4,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 2
        }
    ]
}

###

DELETE http://localhost:8000/orders/b12d0250-d175-404d-9f04-975c67400f57/ HTTP/1.1
Authorization: Bearer <access token>

###